### ISSUE TITLE
Test calling DDlog from Java

### ISSUE THREAD

**Issue by ryzhyk** [ryzhyk/differential-datalog#110]
It should be possible to load a compiled DDlog program and execute transactions from Java.

This requires a couple of preparatory steps:
- DDlog currently generates static libraries. We have to change the crate type to build .so instead.
- DDlog still does not have a complete C API.

Background:
- The generated library file is written to the `target/release` directory, e.g., `tests/datalog_tests/path/target/release/libpath.a`.
- Associated header file is `tests/datalog_tests/path/ddlog.h`

**Comment by mbudiu-vmw** [comment]
I think we can close this issue.
