### ISSUE TITLE
Example of integration with persisted storage

### ISSUE THREAD

**Issue by stites** [ryzhyk/differential-datalog#140]
Cool library! I'm trying to tie this into an arxiv storage program (for personal use). and was wondering if you had an example of loading up DDlog from persisted storage. Specifically this:

> In a typical use case, a DDlog program is used in conjunction with a persistent database, with database records being fed to DDlog as ground facts and the derived facts computed by DDlog being written back to the database.

Thank you!

**Comment by ryzhyk** [comment]
The only database "adapter" we have at the moment is for OVSDB (OpenVSwitch DB), and even that is not fully automated yet.

I'll be happy to assist in developing other adapters. What kind of database and programming language are you targeting?

**Comment by mbudiu-vmw** [comment]
We also have support for file I/O in many formats.

**Comment by stites** [comment]
Persistence to a file (or files) would work!

I'm planning on using this for a personal arxiv storage and search program, that I've written in Haskell, which would just have to persist state between boot. I was thinking that integrating with Postgres or other open source relational database might be cleaner than persisting to files, but this is all very new to me. Something sort of came up and I might not get around to this until the next week, though.

**Comment by ryzhyk** [comment]
So we don't exactly have persistence to a file either. We support a simple command language described [here](https://github.com/ryzhyk/differential-datalog/blob/master/doc/testing/testing.md#command-reference), but it is a command format, not a storage format.

If persistence to a file is what you're after, I'd recommend writing your own parser for whatever format you'd like to store your data in and using the DDlog API in [ddlog.h](https://github.com/ryzhyk/differential-datalog/blob/master/rust/template/ddlog.h) to push/pull data to DDlog.

Having said that, I actually think that writing an ODBC adapter might be slightly easier (and more useful!) than writing a parser.  There are a bunch of design choices to be made there, which I am happy to discuss, but a minimal implementation simply reads the DB record-by-record and pushes those records to DDlog.

Do you think you could briefly explain your use case? What type of processing do you want to do with DDlog? What is your input and output data? Why is incremental processing important? What is the state that you want to persist between boots?

**Comment by stites** [comment]
Thanks @ryzhyk! I think I need to do some experimentation before continuing. The use-case is personal and incremental processing bit is purely for learning, but the rough idea is to run a queryable server where I upload pdfs I am reading/am interested in reading, upon upload they are converted to text and made queryable via a small client that speaks datalog. I was sort of imagining that I could use DDlog as the primary source of truth with a small amount of persistence for the converted text and any relationships/statistics computed post-upload (ie: run several predefined queries on citations or topics and store computed results).

I'll close this issue for now and reopen when I have more time to work on this side project -- I think you've answered my question and I also need to do some more digging on my end. Thanks so much!
