### ISSUE TITLE
Status of aggregations in Souffle converter

### ISSUE THREAD

**Issue by gfour** [ryzhyk/differential-datalog#170]
We are investigating the performance of differential-datalog vs Souffle for Doop analyses. Aggregations cause an error in the Souffle converter. For example, this Doop Datalog line:
```
_MethodLookup_ClosestInterface(?simplename, ?descriptor, ?type, ?method) :-
  _MethodLookup_MoreThanOne(?simplename, ?descriptor, ?type),
  ?minLen = min ?len : { _MethodLookup_WithLen(?simplename, ?descriptor, ?type, _, ?len) },
  _MethodLookup_WithLen(?simplename, ?descriptor, ?type, ?method, ?minLen),
  !_MethodLookup_ClassResolution(?simplename, ?descriptor, ?type, _).
```
produces the following error when parsed via convert.py:
```
parglare.exceptions.ParseError: Error at 1:60917:"Len = min *?len : { _" => Expected: ( but found <?(?)>
```
In the [tutorial](https://github.com/ryzhyk/differential-datalog/blob/master/doc/tutorial/tutorial.md), "Aggregation" is marked as "TODO", while in the [language reference](https://github.com/ryzhyk/differential-datalog/blob/master/doc/language_reference/language_reference.md), it reads: "aggregate functions can only be defined in Rust and imported to a DDlog program as extern function."

I understand at least syntax support is needed (convert.pg) but we are not sure how the Rust function plugs in the generated code for the example above.

**Comment by ryzhyk** [comment]
DDlog does support aggregation. @mbudiu-vmw and I will work to add support for it to the script, hopefully today or tomorrow.

I will also replace the TODO in the tutorial with an actual example of aggregation.

To clarify what the language reference says about using Rust to write aggregation functions, this only applies if you want to define new aggregates.  `min`, for example, is already part of the standard library. Do you have a list of all aggregates used in your benchmarks? We'll be happy to add any missing ones to DDlog.

Finally, thanks for taking DDlog for a spin. I will try to fix #165 shortly, as it should improve the performance significantly.

**Comment by mbudiu-vmw** [comment]
Can you share a (complete) program that contains aggregation?
Do you happen to know what the syntax for aggregation is? I am guess that the colon is "such that" and that aggregation function calls do not require parentheses.

**Comment by ryzhyk** [comment]
I found this: https://souffle-lang.github.io/docs/aggregates/

**Comment by gfour** [comment]
Regarding aggregates, Doop uses "min", "max", and "count". These operators can also be found in [Souffle tests](https://github.com/souffle-lang/souffle/blob/master/tests/evaluation/aggregates/aggregates.dl).

We are trying to run the "micro" analysis of Doop, which is a bit more complex compared to self-contained.dl. The Datalog file can be generated as follows:
1. Run Doop:
``` ./doop -i http://centauri.di.uoa.gr:8081/artifactory/Demo-benchmarks/test-resources/006-hello-world-1.2.jar -a micro --id hello-world --Xstats-none```
2. Resulting logic is in: `out/micro/hello-world/micro.dl`

DDlog seems to almost be there: there are three smaller issues with feeding micro.dl to convert.py but aggregates seem to be the most basic one. For one of the other issues (nested `cat` operations), we should be submitting a PR soon.

**Comment by mbudiu-vmw** [comment]
I have sent a PR which supports a subset of the Souffle aggregation syntax. It currently does not support the syntax with curly braces, so I may need to improve it a bit.

**Comment by mbudiu-vmw** [comment]
@gfour : please let me know if this does not unblock you. Our Souffle converter is rather hacky, we should do it properly if you guys plan to use our tool, but perhaps it's good enough for now.

**Comment by ryzhyk** [comment]
@gfour, I haven't merged the PR yet, as I haven't had a chance to review it (will hopefully have time tomorrow), plus I need to update the Travis configuration so that souffle tests don't time out.  But the PR seems to work fine, including aggregation. It would be great if you could give it a try and let us know if you run into issues.

**Comment by ryzhyk** [comment]
The PR is now merged.  Let us know if you run into issues.

**Comment by gfour** [comment]
There still seems to be a problem. I convert micro.dl and the result is converted_logic.dl (both attached as .txt files). The offending micro.dl rule is:
```
_MethodLookup_ClosestInterface(?simplename, ?descriptor, ?type, ?method) :-
  _MethodLookup_MoreThanOne(?simplename, ?descriptor, ?type),
  ?minLen = min ?len : { _MethodLookup_WithLen(?simplename, ?descriptor, ?type, _, ?len) },
  _MethodLookup_WithLen(?simplename, ?descriptor, ?type, ?method, ?minLen),
  !_MethodLookup_ClassResolution(?simplename, ?descriptor, ?type, _).
```
which becomes:
```
RBasic__MethodLookup_ClosestInterface(_simplename, _descriptor, _type, _method) :-
  RBasic__MethodLookup_MoreThanOne(_simplename, _descriptor, _type),
  RBasic__MethodLookup_WithLen(_simplename, _descriptor, _type, _, _len),
  var _minLen = Aggregate((_instruction, _begin, _dynRetType, _simplename, _bootSignature, _sig, _interface, _pos, _jvmDescriptor, _rawId, _descriptor, _var, _from, _dynParamTypes, _line, _modifier, _field, _target, _method2, _end, _arity, _method1, _const, _dynArity, _superclass, _class, _inmethod, _type, _insn, _cons, _handler, _previous, _retType, _componentType, _signature, _value, _paramTypes, _instanceType, _base, _to, _heap, _declaringType, _mod, _params, _method, _linenumber, _invocation, _annotation, _exceptionType, _index, _key, _tag, _arrayType, _dynName, _supertype, _id, _returnType, _path), group_min(_len)),
  RBasic__MethodLookup_WithLen(_simplename, _descriptor, _type, _method, _minLen),
  not RBasic__MethodLookup_ClassResolution(_simplename, _descriptor, _type, _).
```
That last rule causes this error:
```
ddlog: error: converted_logic.dl:817:842-817:846: Unknown variable: _instruction
```
[micro.dl.txt](https://github.com/ryzhyk/differential-datalog/files/3142418/micro.dl.txt)
[converted_logic.dl.txt](https://github.com/ryzhyk/differential-datalog/files/3142419/converted_logic.dl.txt)

**Comment by mbudiu-vmw** [comment]
Indeed, our handling of aggregates that have a rule (enclosed with { }) is currently incorrect.
We will try to figure out the right translation of such rules today.

**Comment by mbudiu-vmw** [comment]
We are struggling a bit to understand the semantics of an aggregation and how it relates to its context.
For example, what does this compute:
```
res2(X,Y,W) :- a(X,_), Z = 2, Y = min Z : a(X,Z), W = max Z : a(X,Z).
```
Is there a relationship between the three Zs that appear or can some Zs be alpha-renamed?
I.e., is this the same as:

```
res2(X,Y,W) :- a(X,_), Z = 2, Y = min Z1 : a(X,Z1), W = max Z2 : a(X,Z2).
```

**Comment by mbudiu-vmw** [comment]
I have completely overhauled the souffle converter program; I have started from the yacc grammar and added most of it. I am still not supporting some features, but it converts the program you sent. This is still work-in-progress, so it is in the yaccGrammar branch. My testing isn't yet very comprehensive, but if you are brave you can try the tools.

**Comment by mbudiu-vmw** [comment]
We hope we understand how aggregations work....

**Comment by yanniss** [comment]
Simply as a comment on the understanding of aggregates, I'd say the three Zs in the example are unrelated.

**Comment by gfour** [comment]
As an update, the yaccGrammar branch (#203) no longer displays the error when converting the `min` aggregation of our test logic.

**Comment by mbudiu-vmw** [comment]
We have merged a new version of the souffle-converter.py.
(We will change the name to souffle_converter.py, since this is not a legal module name.)
The current usage is:
```
souffle-converter.py souffle.dl prefix
```
From a file called souffle.dl this will generate 3 files: prefix.dl, a DDlog program, prefix.dat, a script which contains all .input data in the Souffle program, and prefix.dump.expected, a file which contains all .output data in the Souffle program in the format produced by DDlog.

I am currently finalizing another script which runs the Souffle tests from the Souffle repository by downloading them and compiling them. It does not support all Souffle features (see #174), but we will enhance it.

**Comment by gfour** [comment]
The latest version of Doop supports DDlog with a `--via-ddlog` command-line option and indeed aggregation no longer causes a compile error. We cannot yet evaluate correctness of execution due to a runtime error (#241).
