### ISSUE TITLE
The re_match function in souffle_lib.dl is not implemented

### ISSUE THREAD

**Issue by mbudiu-vmw** [ryzhyk/differential-datalog#190]
This function needs a native Rust implementation; it checks whether a string matches a regular expression.

**Comment by ryzhyk** [comment]
Is there a list of all souffle functions somewhere? Can we group them in one issue?

**Comment by mbudiu-vmw** [comment]
I think this is the only one missing. The rest are already in souffle_lib.

**Comment by ryzhyk** [comment]
but there's also `group_sum`?

**Comment by mbudiu-vmw** [comment]
that is an aggregate (special syntax in souffle). but yes, that's the second one we are missing.

**Comment by mbudiu-vmw** [comment]
I can try to write some of the rust stuff, but I am still working on finding more bugs for now

**Comment by ryzhyk** [comment]
Don't bother. I'll do it.

**Comment by mbudiu-vmw** [comment]
We need re_match, exp (exponential), group_sum (probably in std)

**Comment by mbudiu-vmw** [comment]
```
extern function re_match(pattern: IString, s: IString): bool
extern function exp(base: bit<32>, exp: bit<32>): bit<32>
```

**Comment by gfour** [comment]
Is re_match still missing? I see that test "souffle13" (which tests `match()`) is still commented out in Spec.hs. Enabling it and running `stack test --ta '-p souffle13'` fails with the following error:
```
 error[E0425]: cannot find function `souffle_lib_re_match` in this scope
            --> lib.rs:1762:59     
             |                  
        1762 |                                                       if !souffle_lib_re_match((&intern_string_intern((&String::from(r###"a.*"###)))), _x) {return None;};
             |                                                           ^^^^^^^^^^^^^^^^^^^^ did you mean `souffle_lib_cat`?
```

**Comment by mbudiu-vmw** [comment]
This is only fixed in the yaccGrammar branch, which has not been merged.
You can see the souffle_lib in lib/souffle_lib.dl. We translate a match in Souffle to a re_match, which in turn calls regex_match. If you work in that branch it should hopefully be correct. I still have some work on the converter before I am ready to send a pull request.

**Comment by gfour** [comment]
Thank you for the update. We will test again when that PR is merged into master. (Right now I cannot test souffle13 in the yaccGrammar branch but I guess that's normal, as it is work in progress.)
