### ISSUE TITLE
Variable not found

### ISSUE THREAD

**Issue by mbudiu-vmw** [ryzhyk/differential-datalog#192]
Compiling the following seemingly legal program:
```
import intern
import souffle_lib
typedef Tnumber = bit<32>
typedef Tsymbol = IString
relation Ra(_n:Tsymbol, _x:Tnumber)
Ra(string_intern("A"), 3).
Ra(string_intern("A"), 4).
output relation Rres2(_n:Tsymbol, _x:Tnumber, _y:Tnumber)
Rres2(_X, _Y, _W) :- Ra(_X, _), Ra(_X, _Z), var tmp_20 = Aggregate((_X), group_min(_Z)), var _Y = tmp_20[31:0], Ra(_X, _Z), var tmp_21 = Aggregate((_Z, _X), group_max(_Z)), var _W = tmp_21[31:0].
```

produces the following error:

```
ddlog -i souffle.dl -L ../../lib
ddlog: error: souffle.dl:9:11-9:13: Unknown variable: _Y
```

**Comment by ryzhyk** [comment]
In DDlog, the only variables visible after an `Aggregate` operator are the group-by variables and the fresh variable on the left-hand-side of the aggregate. It appears that souffle has different semantics.

**Comment by mbudiu-vmw** [comment]
I don't understand, I am defining _Y myself. var _Y = tmp_20[31:0].
If I delete the tail of the rule it works.

**Comment by ryzhyk** [comment]
Yes, but then you aggregate by `(_X,_Z)`.  After this point `_Y` is gone.

**Comment by ryzhyk** [comment]
Removing the `bug` label. If anything, this is a usability issue.
