### ISSUE TITLE
Different version of facts

### ISSUE THREAD

**Issue by Argc0** [ryzhyk/differential-datalog#209]
I was running one of my examples to test the new PR(#203 ) and I noticed that it does not print any results (output) , my dump file is empty. But when I run your example souffle0 everything seems fine. Am I doing something wrong, I don't understand why this happened?

**Comment by ryzhyk** [comment]
Are you able to share the example?

**Comment by mbudiu-vmw** [comment]
Only .output relations are dumped. If the relation has no elements there will be no output.

**Comment by Argc0** [comment]
So I figured it out, this problem occured because we have different versions of facts (that are produced from Doop). There has been a change in the rule: 
```Method_Descriptor(?method, ?descriptor) :-
  Method_ReturnType(?method, ?returnType),
  Method_Params(?method, ?params),
  ?descriptor = cat(?returnType, ?params).
```
 (line 221 in yours self-contained.dl) to
 ```Method_Descriptor(?method, ?descriptor) :-
  Method_ReturnType(?method, ?returnType),
  Method_ParamTypes(?method, ?params),
  ?descriptor = cat(?returnType, cat("(", cat(?params, ")"))).
```
 that add some parentheses. 

For that reason the older version of self-contained.dl couldn't compute the new facts that was given. If you wish to run the example to see for yourselves that the output produced is empty you should run in Doop the command: 
  ```./doop -i http://centauri.di.uoa.gr:8081/artifactory/Demo-benchmarks/test-resources/006-hello-world-1.2.jar -a micro --id hello-world --Xstats-none --Xstop-at-facts thesis-facts```

 it will produce the facts inside the folder thesis-facts , continue by using your own self-contained.dl convert it with souffle-convert.py and run it. If you change the line as I mentioned above and replace it, the output will be appeared.

**Comment by mbudiu-vmw** [comment]
We are not keeping souffle0/self-contained.dl up-to-date. It's just a test that we added.

**Comment by ryzhyk** [comment]
@Argc0, sounds like the problem has been resolved then?

**Comment by Argc0** [comment]
Yes, it has been, Sorry for the upheaval.
