### ISSUE TITLE
Single quotes in strings are escaped on output

### ISSUE THREAD

**Issue by mbudiu-vmw** [ryzhyk/differential-datalog#229]
For example, the following string "Luke isn't a good buddy!" in a relation is dumped as follows:
`Rresult{"Luke isn\'t a good buddy!"}`

**Comment by ryzhyk** [comment]
Fixed by 3f2630f1e631ded33f1641958f21609cd6244799

**Comment by mbudiu-vmw** [comment]
This still does not work for interned strings.
