### ISSUE TITLE
Global variable in `ddlogapi.c`

### ISSUE THREAD

**Issue by ryzhyk** [ryzhyk/differential-datalog#258]
We have users who want to create multiple instances of the same DDlog program.  The `toDelete` global variable will break things for them:

https://github.com/ryzhyk/differential-datalog/blob/006845fb67a4ab0e6cec29bf6a2729714ff7ebc1/java/ddlogapi.c#L27

**Comment by mbudiu-vmw** [comment]
What does "invalid" mean?

**Comment by ryzhyk** [comment]
I think it means that the code does not look right, but it does not lead to a known bug yet (in this case, because  we are not running multiple instances yet). I might be wrong.

**Comment by mbudiu-vmw** [comment]
I thought that the labels apply to the issues, and this would mean that this is an invalid issue.
The right label is "bug", or "enhancement".

**Comment by ryzhyk** [comment]
fair enough
