### ISSUE TITLE
support for multi-file specs

### ISSUE THREAD

**Issue by ryzhyk** [ryzhyk/differential-datalog#69]
The most important use case is combining auto-generated schema (e.g., from OVSDB) with hand-written code. We may be able to get away with using CPP or m4, but must make sure that line numbers in error message refer to original input files.

**Comment by mbudiu-vmw** [comment]
The way this done in P4 is using cpp and then obeying `#line` directives.
So you have to parse `#line` directives and maintain source position based on that.

**Comment by ryzhyk** [comment]
Makes sense. Another option is to use m4, in case we need other preprocessing features in addition to `#include` (in which case m4 is a much nice preprocessor than C++).

I am also thinking that we should co-design this feature with the name space system. I like how modern languages force file names to match module (or namespace) names.

**Comment by mbudiu-vmw** [comment]
Macros are evil.
You can use cpp for now, and add support for an import later once you have a design.
Supporting `#line` directives is useful anyway. That's the only thing you really need - plus a program that calls cpp.

**Comment by ryzhyk** [comment]
Resolved by #101
