### ISSUE TITLE
Use P4 syntax for bitvector literals

### ISSUE THREAD

**Issue by mbudiu-vmw** [ryzhyk/differential-datalog#79]
https://p4.org/p4-spec/docs/P4-16-v1.0.0-spec.html#sec-literals

**Comment by mbudiu-vmw** [comment]
If you want to do this we should to it as soon as possible, before we have too many people writing programs.

**Comment by ryzhyk** [comment]
Actually, I am not sure. Both syntaxes are similarly quirky. I don't see how the P4 one is significantly better.

**Comment by mbudiu-vmw** [comment]
The single quote trips up many tools. For example, if you want to use the C preprocessor it will be very upset.

**Comment by mbudiu-vmw** [comment]
We have to revisit this: we need a syntax for signed literals. P4 has one, and I don't see how to tweak the ddlog syntax in a nice way.
